name: Scheduled Action Context Example

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context to file
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          printenv --version
          printenv GITHUB_CONTEXT > tee scheduled_action_context.json

      - name: Display context
        run: cat ./scheduled_action_context.json
