name: Scheduled Action Context Example

on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context to file
        run: |
          echo '${{ github.event }}' | jq > scheduled_action_context.json

      - name: Display context
        run: cat ./scheduled_action_context.json
