name: Scheduled Action Context Example

on:
  schedule:
    - cron: "17 4 * * *"
  workflow_dispatch:

jobs:
  scheduled:
    name: Scheduled
    runs-on: ubuntu-latest
    steps:
      - name: Echo context to file
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          printenv GITHUB_CONTEXT > scheduled_action_context.json
          echo '# Scheduled Action Context' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          printenv GITHUB_CONTEXT >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
