name: Scheduled Action
run-name: on.${{ github.event_name }}

on:
  schedule:
    - cron: "17 4 * * *" # 4:17 AM UTC every day
  workflow_dispatch:

jobs:
  schedule:
    name: "on.${{ github.event_name }}"
    uses: brendancogan/github-actions-context/.github/workflows/print.yml@main

  schedule2:
    name: "on.${{ github.event_name }}"
    uses: brendancogan/github-actions-context/.github/workflows/print_context.yml@main
